// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type Channel struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type Message struct {
	ID        string    `json:"id"`
	Content   string    `json:"content"`
	Owner     string    `json:"owner"`
	CreatedAt time.Time `json:"createdAt"`
}

type Mutation struct {
}

type Query struct {
}

type Subscription struct {
}
